name: MLOps CI/CD to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Purane duplicate remote ko delete karna ta k error na aaye
        git remote remove hf || true
        
        # Sahi URL bina end-slash ke setup karna
        git remote add hf https://amnakhaalid1:$HF_TOKEN@huggingface.co/spaces/amnakhaalid1/my-ml-app
        
        # Branch ko direct cloud par merge aur force push karna
        git push --force hf main:main

