name: MLOps CI/CD to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Hugging Face ke git server par directly code aur Dockerfile push karna
        # Note: Neeche amnakhaalid87 aur my-ml-app ki jagah apna HF username aur space name match karein
        git remote add hf https://amnakhaalid87:$HF_TOKEN@huggingface.co/spaces/amnakhaalid87/my-ml-app
        git push --force hf main
