name: Professional MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ----------------------------------------
    # PART 1: DOCKER HUB AUTOMATION (CI)
    # ----------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image to Hub
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-ml-app:latest

    # ----------------------------------------
    # PART 2: HUGGING FACE NEW CD ENGINE (AUTOMATION)
    # ----------------------------------------
    - name: Install New Hugging Face Hub CLI
      run: pip install --upgrade huggingface_hub

    - name: Deploy Code via New HF Tool
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # Secure login setup
        hf auth login --token $HF_TOKEN
        
        # Exact files update command (Notice the target repository string matching)
        hf upload amnakhaalid1/my-ml-app . --repo-type=space --commit-message "Production automated deployment via HF Tool from GitHub Actions"
